version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: lms-db
    environment:
      POSTGRES_DB: lms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
    ports:
      - "5433:5432" 
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: jchishugi/lms-backend:latest
    container_name: lms-backend
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/lms
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - STORAGE_TYPE=local
      - LOCAL_STORAGE_PATH=/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    image: jchishugi/lms-frontend:latest
    container_name: lms-frontend
    ports:
      - "3000:3000"
    environment:
       - NODE_ENV=development
       - NEXT_PUBLIC_API_URL=http://localhost:8080/api
       - NEXT_PUBLIC_ALLOWED_DOMAINS=ist.com
       - NEXT_PUBLIC_AZURE_CLIENT_ID=a182ac8e-b6fb-4775-b902-03cd5ca2defb
       - NEXT_PUBLIC_AZURE_AUTHORITY=https://login.microsoftonline.com/consumers
       - NEXT_PUBLIC_AZURE_REDIRECT_URI=http://localhost:3000/login
       - NEXT_PUBLIC_AZURE_POST_LOGOUT_REDIRECT_URI=http://localhost:3000/login
       - NEXT_PUBLIC_AZURE_SCOPES=openid profile email User.Read
       - NEXT_PUBLIC_AZURE_GRAPH_ENDPOINT=https://graph.microsoft.com/v1.0
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres-data: